# For the standard ErgoDox Wireless dongle setup with the latest Raytac "green"
# dongle, you do not need to modify this file. If you are using a different
# dongle such as the older Raytac "blue" dongle, you will need to modify
# "board". For a dongleless setup, you will need to modify both "board" and
# "shield". Please see "readme.md" for more details.

# TODO TODO TODO add slicemk_ergodox_202109 and slicemk_ergodox_202212 for
# dongleless. see trello card.

# TODO TODO TODO think about whether this "matrix" branch should go under
# slicemk user or stay

include:

# TODO TODO TODO test dongles.
  - board: nordic_nrf52840_dongle_slicemk
    shield: slicemk_ergodox_dongle
  - board: raytac_mdbt50q_cx_blue
    shield: slicemk_ergodox_dongle
  - board: raytac_mdbt50q_rx
    shield: slicemk_ergodox_dongle
  - board: raytac_mdbt50q_rx_green
    shield: slicemk_ergodox_dongle
  - board: slicemk_1551usb3_ms88sfa_blue
    shield: slicemk_ergodox_dongle
  - board: slicemk_usbc_mdbt50q_blue
    shield: slicemk_ergodox_dongle

# TODO TODO TODO test dongleless
  - board: slicemk_ergodox_202104
    shield:  slicemk_ergodox_leftcentral
  - board: slicemk_ergodox_202108_blue_left
    shield: slicemk_ergodox_leftcentral
  - board: slicemk_ergodox_202108_green_left
    shield: slicemk_ergodox_leftcentral
  - board: slicemk_ergodox_202205_green_left
    shield: slicemk_ergodox_leftcentral
  - board: slicemk_ergodox_202207_green_left
    shield: slicemk_ergodox_leftcentral
